#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    vehicle = bld.path.name
    bld.env.append_value(
        'INCLUDES',
        [   
            'libraries/vl53l1x_api/core/inc',       # for Crazyflie support
            'libraries/vl53l1x_api/platform/inc',   # for Crazyflie support
        ],
    )
    bld.ap_stlib(
        name=vehicle + '_libs',
        ap_vehicle=vehicle,
        ap_libraries=bld.ap_common_vehicle_libraries() + [
            'AC_AttitudeControl',
            'AC_InputManager',
            'AC_PrecLand',
            'AC_Sprayer',
            'AC_Autorotation',
            'AC_WPNav',
            'AP_Camera',
            'AP_IRLock',
            'AP_InertialNav',
            'AP_Motors',
            'AP_Avoidance',
            'AP_AdvancedFailsafe',
            'AP_SmartRTL',
            'AP_WheelEncoder',
            'AP_Winch',
            'AP_LTM_Telem',
            'AP_Devo_Telem',
            'AC_AutoTune',
            'AP_KDECAN',
            'AP_SurfaceDistance',
            'vl53l1x_api',     # Added for FlowDeck Support via ST VL53L1x API
        ],
    )
    print("STATIC_LIBS for %s:" % vehicle, bld.env.STATIC_LIBS) #DEBUG

    bld.ap_program(
        program_name='arducopter',
        program_groups=['bin', 'copter'],
        #use=vehicle + '_libs',
        use=[vehicle + '_libs', 'vl53l1x_api'],
        defines=['FRAME_CONFIG=MULTICOPTER_FRAME'],
        )

    bld.ap_program(
        program_name='arducopter-heli',
        program_groups=['bin', 'heli'],
        use=vehicle + '_libs',
        defines=['FRAME_CONFIG=HELI_FRAME'],
        )  
